# Generated by Django 3.0.5 on 2020-05-21 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_community_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
