# Generated by Django 3.0.5 on 2020-05-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_community_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
