# Generated by Django 3.0.5 on 2020-05-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20200522_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='pic',
        ),
    ]
