# Generated by Django 3.0.5 on 2020-05-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_downvote_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='downvote',
            name='date_voted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='upvote',
            name='date_voted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
