# Generated by Django 3.0.5 on 2020-06-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_replyanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
