# Generated by Django 3.0.5 on 2020-06-11 08:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_auto_20200608_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='desc',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
