# Generated by Django 3.0.5 on 2020-06-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_answer_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='username',
        ),
        migrations.DeleteModel(
            name='Downvote',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
